import { writeFileSync, mkdirSync } from "fs";

mkdirSync("docs", { recursive: true });

writeFileSync("docs/contextual-retrieval.md", `
# Contextual Retrieval

## The problem with standard RAG chunking

In standard RAG pipelines, documents are split into chunks and each chunk is embedded independently. This creates a critical information loss problem. Consider a chunk that contains:

"The model returns a 404 error when the endpoint is unreachable."

Without context, the embedding for this chunk does not capture what model, what endpoint, or what operation is being described. When a user asks "why does the Gemini streaming API fail?", this chunk may not be retrieved even though it directly answers the question.

This problem affects an estimated 67% of retrieval failures in production RAG systems.

## The contextual retrieval solution

Anthropic's contextual retrieval technique, published in September 2024, addresses this by prepending a short chunk-specific context before embedding. The context is generated by an LLM that reads the full document and summarises where each chunk fits.

The same chunk becomes:

"This chunk is from the Gemini API error handling section and describes the HTTP 404 response returned when the streaming endpoint URL is malformed or unreachable. The model returns a 404 error when the endpoint is unreachable."

Now the embedding captures the full semantic meaning. Retrieval failures drop by approximately 49%.

## Implementation

The process has two steps at ingest time only — no changes to query time:

1. For each chunk, call an LLM with the full document and the chunk
2. Ask it to write 1-2 sentences describing where the chunk fits in the document
3. Prepend those sentences to the chunk text before embedding
4. Store the original chunk text separately for display purposes

The embedded text is: context + original chunk
The displayed text is: original chunk only

## Cost considerations

Context generation runs once at ingest time, not at query time. Using a cheap model like gemini-2.5-flash-lite at \$0.10 per million tokens, generating context for 1000 chunks costs approximately \$0.02. This one-time cost is repaid on every query through improved retrieval accuracy.

## When contextual retrieval helps most

It is most impactful for technical documentation with cross-references, codebases where variable names appear without declaration context, research papers with forward references, and any corpus where chunks are incomplete thoughts without their surrounding document context.

It provides diminishing returns for self-contained factual lists, FAQs where each entry is already complete, and short documents under 1000 words where chunking is minimal.

## Comparison with other chunking strategies

Standard chunking: split on paragraphs or fixed character count, embed as-is.
Contextual retrieval: split on paragraphs, generate context, embed context + chunk.
Semantic chunking: use embedding similarity to detect topic shifts and split at boundaries.
Late chunking: embed the full document first using long-context embeddings, then pool embeddings per chunk.

For most production RAG systems in 2025-2026, contextual retrieval offers the best improvement-to-implementation-effort ratio.

## Node.js implementation pattern

The context generation prompt that works reliably:

Given the full document and a specific chunk, ask the model:
"In 1-2 concise sentences, describe what this chunk is about and where it fits in the document. Output only the context sentences."

Use temperature 0 for consistency. Use the cheapest available model since quality requirements are low — you just need a factual description, not creative writing.
`.trim());

writeFileSync("docs/rag-chunking-strategies.md", `
# RAG Chunking Strategies

## Why chunking is the hardest part of RAG

The retrieval quality of a RAG system is determined almost entirely by chunking strategy. A state-of-the-art embedding model with poor chunks will underperform a basic model with well-constructed chunks. This is counterintuitive — developers tend to focus on model selection when they should focus on data preparation.

## Fixed-size chunking

The simplest approach: split text every N characters or tokens with optional overlap.

Advantages: simple to implement, predictable chunk sizes, easy to reason about token costs.
Disadvantages: frequently splits mid-sentence or mid-code-block, producing semantically incomplete chunks that embed poorly and confuse the generator.

Recommended overlap: 10-20% of chunk size. A 500-character chunk should have 50-100 characters of overlap with the next chunk.

When to use: quick prototypes, corpora with naturally uniform paragraph lengths, structured data like CSV or JSON.

## Paragraph-aware chunking

Split on double newlines first, then fall back to sentence splitting if a paragraph exceeds the size limit. Carry overlap between chunks.

This respects natural document structure. A paragraph is usually a complete thought. Splitting within it loses that completeness.

This is what most production RAG systems use as their baseline. It outperforms fixed-size chunking on recall metrics by 15-25% on typical technical documentation.

## Semantic chunking

Use an embedding model to detect topic shifts. Embed each sentence, compute cosine similarity between adjacent sentences, and split when similarity drops below a threshold.

Advantages: chunks align with actual topic boundaries, not arbitrary character counts.
Disadvantages: requires embedding every sentence at ingest time (expensive), threshold tuning is non-trivial, can produce very uneven chunk sizes.

Use when: your corpus has long documents that shift topics frequently, like academic papers or long-form articles. Not worth the complexity for short technical docs.

## Late chunking

Embed the entire document using a long-context embedding model. Then split the resulting token embeddings by position to produce per-chunk embeddings that retain full document context.

This is fundamentally different from the others: you embed first, then chunk — not chunk then embed.

Advantages: every chunk embedding has full document context by construction, no LLM calls needed for context generation.
Disadvantages: requires a long-context embedding model (jina-embeddings-v2 or similar), not yet supported by most providers including Gemini, chunking positions must align with token boundaries.

Status in 2025-2026: promising but not yet practical for most teams due to limited model support.

## Chunk size recommendations

For technical documentation: 300-600 characters (~75-150 tokens) works well. Small enough to be specific, large enough to contain a complete thought.

For code: chunk by function or class, not by character count. A 50-line function should be one chunk, not split arbitrarily at line 25.

For mixed content: use larger chunks (800-1200 characters) with higher overlap (20-25%) since the content density varies.

## The overlap problem

Overlap prevents information loss at chunk boundaries. If a key sentence spans two chunks, it appears fully in at least one of them.

But too much overlap inflates your vector store size and can confuse retrieval by returning near-duplicate chunks. A good heuristic: if you see the same sentence in two retrieved chunks, your overlap is too high.

## Metadata matters

Every chunk should store at minimum: source filename, chunk index, and creation timestamp. Ideally also: section heading, document type, and any structured metadata from the source (author, date, tags).

Metadata enables filtered retrieval — searching only chunks from a specific source, or only chunks from documents tagged as authoritative. This is significantly faster and more precise than semantic search alone for known-source queries.

## Testing your chunking strategy

The fastest way to evaluate chunking: take 10 questions you expect the system to answer, run retrieval only (no generation), and check whether the top-3 chunks for each question actually contain the answer. If fewer than 8 out of 10 do, your chunking needs work.

This is a recall@3 metric. Production RAG systems typically target recall@3 above 80% before moving on to generation quality.
`.trim());

writeFileSync("docs/agent-memory-patterns.md", `
# Agent Memory Patterns

## Why stateless agents fail in production

A stateless agent — one that starts fresh every session — forces users to re-establish context on every interaction. This is acceptable for single-turn tasks (classify this text, summarise this document) but fails for ongoing work relationships.

A research assistant that forgets you prefer Node.js over Python will repeatedly give Python examples. A coding agent that forgets you are working in a monorepo will keep giving advice for single-package setups. The cognitive overhead of re-establishing context falls on the user, which defeats the purpose of an assistant.

## The two memory types every agent needs

Short-term memory holds the current conversation. It is the messages array passed to the model on every call. It is fast, requires no database, and is lost when the session ends. Every agent already has this — it is what makes a conversation coherent within a single session.

Long-term memory holds facts, preferences, conclusions, and references that persist across sessions. It requires a storage backend and a retrieval mechanism. Without it, every session is the agent's first day on the job.

## Implementing long-term memory with vector search

The most flexible approach stores memories as text with embeddings in a vector database. On each turn, retrieve the top-k memories most semantically similar to the current user message and inject them into the system prompt.

This approach treats memory the same way RAG treats documents. The agent's past experiences become a searchable knowledge base. The same infrastructure that powers document retrieval powers memory recall.

## Memory types and importance scoring

Not all memories are equal. A user's explicit statement of preference is more important than a casual mention of a topic. Assigning importance scores at store time and using them as a ranking multiplier at recall time surfaces the right memories.

Suggested importance scores:
- Explicit conclusions reached in conversation: 0.9
- Stated user preferences: 0.8  
- Identified relevant sources: 0.6
- General facts encountered: 0.5

## The memory formation pattern

Let the model signal what to remember inline in its response, then extract and store those signals programmatically. This is cleaner than asking the model to return structured JSON alongside its response.

A pattern like [REMEMBER: preference: user prefers concise code over verbose explanations] embedded in the response text can be extracted with a simple regex, stored, and stripped from the displayed text. The user never sees the memory machinery.

## Memory recall and injection

Recall memories at the start of each turn before generating a response. Inject them into the system prompt as a dedicated section. Keep the format simple — a bulleted list of [TYPE] content pairs is readable by the model and traceable by developers.

Limit recalled memories to the top 5-8 most relevant. More than this dilutes the signal and inflates token costs. The importance-weighted similarity ranking ensures the most valuable memories surface first.

## Memory decay and maintenance

Without maintenance, memory stores grow indefinitely and quality degrades as old, irrelevant memories compete with current ones. Two simple mechanisms keep memory healthy:

Access counting: track how many times each memory has been recalled. Memories recalled frequently are genuinely useful. Memories never recalled after initial storage are candidates for deletion.

Recency weighting: multiply importance by a recency factor. A conclusion reached six months ago and never accessed since is less relevant than one reached last week.

## What not to store as memory

Avoid storing raw conversation turns. These are already in the short-term history during a session and produce noise in long-term memory.

Avoid storing facts that are better retrieved from documents. If the agent has access to a RAG system, a memory that says "contextual retrieval improves recall by 49%" is redundant with the documentation — and may become stale if the documentation is updated.

Store instead: preferences, workflow choices, project-specific context, and conclusions that required reasoning to reach. These are things the agent derived, not things it retrieved.

## Memory privacy and user isolation

Every memory must be scoped to a user identifier. A multi-user system that shares memory between users is both a privacy violation and a quality problem. Always filter memory queries by user_id as a non-negotiable constraint, never as an optional optimisation.
`.trim());

console.log("Created 3 docs in ./docs/");
console.log("Run: node rag/ingest.js");